import { SkillDef, SkillTarget } from "./types";

// Knight skills
export const BASH: SkillDef = {
  id: "bash",
  name: "Bash",
  damage: 2.0,
  isMultiplier: true,
  bonusDamage: 50,
  cooldownMs: 3000,
  castTimeMs: 0,
  range: 64,
  radius: 0,
  manaCost: 20,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: { type: "stun", value: 0, durationMs: 300 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const MAGNUM_BREAK: SkillDef = {
  id: "magnum_break",
  name: "Magnum Break",
  damage: 1.5,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 8000,
  castTimeMs: 0,
  range: 0,
  radius: 120,
  manaCost: 40,
  target: SkillTarget.AoE,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 80,
};

export const PROVOKE: SkillDef = {
  id: "provoke",
  name: "Provoke",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 12000,
  castTimeMs: 0,
  range: 200,
  radius: 0,
  manaCost: 15,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: { type: "debuff", value: 0, durationMs: 5000, atkMod: 1.2, defMod: 0.5 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const BERSERK: SkillDef = {
  id: "berserk",
  name: "Berserk",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 30000,
  castTimeMs: 0,
  range: 0,
  radius: 0,
  manaCost: 100,
  target: SkillTarget.Self,
  duration: 0,
  effect: { type: "buff", value: 0, durationMs: 10000, atkMod: 1.5, defMod: 0.7, speedMod: 1.3 },
  ignoreDefPercent: 0,
  knockback: 0,
};

// Assassin skills
export const SONIC_BLOW: SkillDef = {
  id: "sonic_blow",
  name: "Sonic Blow",
  damage: 4.0,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 5000,
  castTimeMs: 0,
  range: 48,
  radius: 0,
  manaCost: 40,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const CLOAKING: SkillDef = {
  id: "cloaking",
  name: "Cloaking",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 15000,
  castTimeMs: 0,
  range: 0,
  radius: 0,
  manaCost: 50,
  target: SkillTarget.Self,
  duration: 0,
  effect: { type: "invisible", value: 0, durationMs: 5000, speedMod: 1.2 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const POISON_BREATH: SkillDef = {
  id: "poison_breath",
  name: "Poison Breath",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 10000,
  castTimeMs: 0,
  range: 160,
  radius: 0,
  manaCost: 35,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: { type: "poison", value: 30, durationMs: 6000 }, // 30 dmg/s for 6s
  ignoreDefPercent: 0,
  knockback: 0,
};

export const CROSS_IMPACT: SkillDef = {
  id: "cross_impact",
  name: "Cross Impact",
  damage: 5.0,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 20000,
  castTimeMs: 0,
  range: 200,
  radius: 0,
  manaCost: 80,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

// Wizard skills
export const FIRE_BOLT: SkillDef = {
  id: "fire_bolt",
  name: "Fire Bolt",
  damage: 350,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 2000,
  castTimeMs: 500,
  range: 300,
  radius: 0,
  manaCost: 40,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0.5,
  knockback: 0,
};

export const STORM_GUST: SkillDef = {
  id: "storm_gust",
  name: "Storm Gust",
  damage: 250,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 12000,
  castTimeMs: 1000,
  range: 280,
  radius: 150,
  manaCost: 120,
  target: SkillTarget.AoE,
  duration: 0,
  effect: { type: "slow", value: 0.4, durationMs: 3000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const JUPITEL_THUNDER: SkillDef = {
  id: "jupitel_thunder",
  name: "Jupitel Thunder",
  damage: 300,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 6000,
  castTimeMs: 0,
  range: 250,
  radius: 0,
  manaCost: 60,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 120,
};

export const METEOR_STORM: SkillDef = {
  id: "meteor_storm",
  name: "Meteor Storm",
  damage: 500,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 25000,
  castTimeMs: 1500,
  range: 350,
  radius: 200,
  manaCost: 180,
  target: SkillTarget.AoE,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

// Priest skills
export const HEAL: SkillDef = {
  id: "heal",
  name: "Heal",
  damage: -600, // negative = healing
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 3000,
  castTimeMs: 0,
  range: 0,
  radius: 0,
  manaCost: 50,
  target: SkillTarget.Self,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const HOLY_LIGHT: SkillDef = {
  id: "holy_light",
  name: "Holy Light",
  damage: 250,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 4000,
  castTimeMs: 0,
  range: 250,
  radius: 0,
  manaCost: 35,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const KYRIE_ELEISON: SkillDef = {
  id: "kyrie_eleison",
  name: "Kyrie Eleison",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 15000,
  castTimeMs: 0,
  range: 0,
  radius: 0,
  manaCost: 80,
  target: SkillTarget.Self,
  duration: 0,
  effect: { type: "shield", value: 800, durationMs: 10000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const MAGNUS_EXORCISMUS: SkillDef = {
  id: "magnus_exorcismus",
  name: "Magnus Exorcismus",
  damage: 200, // per second
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 25000,
  castTimeMs: 0,
  range: 250,
  radius: 180,
  manaCost: 150,
  target: SkillTarget.AoEZone,
  duration: 5000,
  effect: { type: "dot_zone", value: 200, durationMs: 5000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

// Crusader skills
export const HOLY_CROSS: SkillDef = {
  id: "holy_cross",
  name: "Holy Cross",
  damage: 2.5,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 4000,
  castTimeMs: 0,
  range: 64,
  radius: 0,
  manaCost: 30,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const GRAND_CROSS: SkillDef = {
  id: "grand_cross",
  name: "Grand Cross",
  damage: 300,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 10000,
  castTimeMs: 0,
  range: 0,
  radius: 130,
  manaCost: 60,
  target: SkillTarget.AoE,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const DEVOTION: SkillDef = {
  id: "devotion",
  name: "Devotion",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 15000,
  castTimeMs: 0,
  range: 0,
  radius: 0,
  manaCost: 50,
  target: SkillTarget.Self,
  duration: 0,
  effect: { type: "shield", value: 600, durationMs: 8000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const SHIELD_BOOMERANG: SkillDef = {
  id: "shield_boomerang",
  name: "Shield Boomerang",
  damage: 3.0,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 12000,
  castTimeMs: 0,
  range: 200,
  radius: 0,
  manaCost: 45,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

// Rogue skills
export const BACKSTAB: SkillDef = {
  id: "backstab",
  name: "Backstab",
  damage: 3.5,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 5000,
  castTimeMs: 0,
  range: 48,
  radius: 0,
  manaCost: 35,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const STRIP_ARMOR: SkillDef = {
  id: "strip_armor",
  name: "Strip Armor",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 12000,
  castTimeMs: 0,
  range: 120,
  radius: 0,
  manaCost: 40,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: { type: "debuff", value: 0, durationMs: 6000, defMod: 0.5 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const INTIMIDATE: SkillDef = {
  id: "intimidate",
  name: "Intimidate",
  damage: 2.0,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 8000,
  castTimeMs: 0,
  range: 150,
  radius: 0,
  manaCost: 30,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const CLOSE_CONFINE: SkillDef = {
  id: "close_confine",
  name: "Close Confine",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 20000,
  castTimeMs: 0,
  range: 48,
  radius: 0,
  manaCost: 60,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: { type: "stun", value: 0, durationMs: 3000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

// Sage skills
export const FIRE_WALL: SkillDef = {
  id: "fire_wall",
  name: "Fire Wall",
  damage: 200,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 8000,
  castTimeMs: 0,
  range: 200,
  radius: 100,
  manaCost: 50,
  target: SkillTarget.AoEZone,
  duration: 4000,
  effect: { type: "dot_zone", value: 200, durationMs: 4000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const DISPELL: SkillDef = {
  id: "dispell",
  name: "Dispell",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 15000,
  castTimeMs: 0,
  range: 250,
  radius: 0,
  manaCost: 40,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: { type: "debuff", value: 0, durationMs: 1, atkMod: 1.0, defMod: 1.0, speedMod: 1.0 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const VOLCANO_BUFF: SkillDef = {
  id: "volcano_buff",
  name: "Volcano Buff",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 12000,
  castTimeMs: 0,
  range: 0,
  radius: 0,
  manaCost: 45,
  target: SkillTarget.Self,
  duration: 0,
  effect: { type: "buff", value: 0, durationMs: 10000, atkMod: 1.3 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const EARTH_SPIKE: SkillDef = {
  id: "earth_spike",
  name: "Earth Spike",
  damage: 400,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 6000,
  castTimeMs: 0,
  range: 250,
  radius: 0,
  manaCost: 55,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0.4,
  knockback: 0,
};

// Monk skills
export const OCCULT_IMPACTION: SkillDef = {
  id: "occult_impaction",
  name: "Occult Impaction",
  damage: 3.0,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 5000,
  castTimeMs: 0,
  range: 48,
  radius: 0,
  manaCost: 35,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0.8,
  knockback: 0,
};

export const INVESTIGATE: SkillDef = {
  id: "investigate",
  name: "Investigate",
  damage: 2.5,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 4000,
  castTimeMs: 0,
  range: 48,
  radius: 0,
  manaCost: 25,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const ZEN: SkillDef = {
  id: "zen",
  name: "Zen",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 15000,
  castTimeMs: 0,
  range: 0,
  radius: 0,
  manaCost: 50,
  target: SkillTarget.Self,
  duration: 0,
  effect: { type: "buff", value: 0, durationMs: 12000, atkMod: 1.4 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const ASURA_STRIKE: SkillDef = {
  id: "asura_strike",
  name: "Asura Strike",
  damage: 8.0,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 30000,
  castTimeMs: 0,
  range: 64,
  radius: 0,
  manaCost: 200,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

// Hunter skills
export const DOUBLE_STRAFE: SkillDef = {
  id: "double_strafe",
  name: "Double Strafe",
  damage: 3.0,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 3000,
  castTimeMs: 0,
  range: 300,
  radius: 0,
  manaCost: 25,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const ARROW_SHOWER: SkillDef = {
  id: "arrow_shower",
  name: "Arrow Shower",
  damage: 2.0,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 8000,
  castTimeMs: 0,
  range: 250,
  radius: 120,
  manaCost: 40,
  target: SkillTarget.AoE,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const ANKLE_SNARE: SkillDef = {
  id: "ankle_snare",
  name: "Ankle Snare",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 15000,
  castTimeMs: 0,
  range: 200,
  radius: 60,
  manaCost: 35,
  target: SkillTarget.AoE,
  duration: 0,
  effect: { type: "stun", value: 0, durationMs: 3000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const BLITZ_BEAT: SkillDef = {
  id: "blitz_beat",
  name: "Blitz Beat",
  damage: 500,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 12000,
  castTimeMs: 0,
  range: 280,
  radius: 0,
  manaCost: 60,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 1.0,
  knockback: 0,
};

// Bard skills
export const MELODY_STRIKE: SkillDef = {
  id: "melody_strike",
  name: "Melody Strike",
  damage: 2.5,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 4000,
  castTimeMs: 0,
  range: 250,
  radius: 0,
  manaCost: 25,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const FROST_JOKER: SkillDef = {
  id: "frost_joker",
  name: "Frost Joker",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 15000,
  castTimeMs: 0,
  range: 0,
  radius: 130,
  manaCost: 50,
  target: SkillTarget.AoE,
  duration: 0,
  effect: { type: "stun", value: 0, durationMs: 2000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const DRUM_BATTLE: SkillDef = {
  id: "drum_battle",
  name: "Drum of Battle",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 12000,
  castTimeMs: 0,
  range: 0,
  radius: 0,
  manaCost: 40,
  target: SkillTarget.Self,
  duration: 0,
  effect: { type: "buff", value: 0, durationMs: 10000, atkMod: 1.2, speedMod: 1.1 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const LOKIS_VEIL: SkillDef = {
  id: "lokis_veil",
  name: "Loki's Veil",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 25000,
  castTimeMs: 0,
  range: 280,
  radius: 150,
  manaCost: 100,
  target: SkillTarget.AoE,
  duration: 0,
  effect: { type: "stun", value: 0, durationMs: 4000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

// Dancer skills
export const SLINGING_ARROW: SkillDef = {
  id: "slinging_arrow",
  name: "Slinging Arrow",
  damage: 2.5,
  isMultiplier: true,
  bonusDamage: 0,
  cooldownMs: 4000,
  castTimeMs: 0,
  range: 250,
  radius: 0,
  manaCost: 25,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const SCREAM: SkillDef = {
  id: "scream",
  name: "Scream",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 15000,
  castTimeMs: 0,
  range: 0,
  radius: 130,
  manaCost: 50,
  target: SkillTarget.AoE,
  duration: 0,
  effect: { type: "stun", value: 0, durationMs: 2000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const HUMMING: SkillDef = {
  id: "humming",
  name: "Humming",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 12000,
  castTimeMs: 0,
  range: 0,
  radius: 0,
  manaCost: 40,
  target: SkillTarget.Self,
  duration: 0,
  effect: { type: "buff", value: 0, durationMs: 10000, speedMod: 1.3 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const CHARM: SkillDef = {
  id: "charm",
  name: "Charm",
  damage: 0,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 20000,
  castTimeMs: 0,
  range: 250,
  radius: 0,
  manaCost: 80,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: { type: "slow", value: 0.6, durationMs: 5000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

// Alchemist skills
export const ACID_TERROR: SkillDef = {
  id: "acid_terror",
  name: "Acid Terror",
  damage: 300,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 4000,
  castTimeMs: 0,
  range: 200,
  radius: 0,
  manaCost: 35,
  target: SkillTarget.SingleEnemy,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0.6,
  knockback: 0,
};

export const DEMONSTRATION: SkillDef = {
  id: "demonstration",
  name: "Demonstration",
  damage: 150,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 15000,
  castTimeMs: 0,
  range: 200,
  radius: 120,
  manaCost: 80,
  target: SkillTarget.AoEZone,
  duration: 5000,
  effect: { type: "dot_zone", value: 150, durationMs: 5000 },
  ignoreDefPercent: 0,
  knockback: 0,
};

export const POTION_PITCHER: SkillDef = {
  id: "potion_pitcher",
  name: "Potion Pitcher",
  damage: -800,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 4000,
  castTimeMs: 0,
  range: 0,
  radius: 0,
  manaCost: 50,
  target: SkillTarget.Self,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};

export const BIO_CANNIBALIZE: SkillDef = {
  id: "bio_cannibalize",
  name: "Bio Cannibalize",
  damage: 400,
  isMultiplier: false,
  bonusDamage: 0,
  cooldownMs: 10000,
  castTimeMs: 0,
  range: 250,
  radius: 100,
  manaCost: 60,
  target: SkillTarget.AoE,
  duration: 0,
  effect: null,
  ignoreDefPercent: 0,
  knockback: 0,
};
